-- The Kylas KPI store, as SQLite for Cloudflare D1.
-- GENERATED by scripts/sql-schema.mjs from scripts/schema.mjs — do not edit by hand.
-- Regenerate:  node scripts/sql-schema.mjs --out db/schema.sql

PRAGMA foreign_keys = ON;

-- One row per Kylas company. Every KPI field here is derived from its Contacts — nothing is entered at this level.
CREATE TABLE IF NOT EXISTS "companies" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  , "name" TEXT
  , "kylas_company_id" TEXT
  -- The Kylas owner's name, copied on every save so this table can attribute a company without calling Kylas.
  , "owner" TEXT
  , "kylas_updated_at" TEXT CHECK ("kylas_updated_at" IS NULL OR "kylas_updated_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  , "kylas_owner_id" TEXT
  , "kylas_stage" TEXT
  , "source_of_data" TEXT
  , "batch" TEXT
  , "account_health" TEXT
  , "website" TEXT
  , "last_called_at" TEXT
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("kylas_company_id")
);

-- One row per Kylas contact. Where data is actually entered. KPI Rank is monotonic and written by the proxy, never by a formula.
CREATE TABLE IF NOT EXISTS "contacts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  , "name" TEXT
  , "kylas_contact_id" TEXT
  , "kylas_updated_at" TEXT CHECK ("kylas_updated_at" IS NULL OR "kylas_updated_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  , "designation" TEXT
  , "linkedin" TEXT
  , "phone" TEXT
  , "phones" TEXT
  , "email" TEXT
  , "emails" TEXT
  , "kylas_owner_id" TEXT
  , "salutation" TEXT
  , "source_of_data" TEXT
  , "remarks" TEXT
  , "owner" TEXT
  , "current_stage" TEXT CHECK ("current_stage" IS NULL OR "current_stage" IN ('SQL_SALES_QUALIFIED_LEAD', 'ACTIVE_REQUIREMENT_CALL_DONE_–_AWAITING_CLIENT_INPUTS', 'ACTIVE_REQUIREMENT_CALL_NO_SHOW', 'ACTIVE_REQUIREMENT_CALL_BOOKED', 'DISCOVERY_CALL_DONE_AWAITING_CLIENT_INPUTS', 'CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'DISCOVERY_CALL_BOOKED', 'FOLLOW_UP_1', 'FOLLOW_UP_2', 'FOLLOW_UP_3', 'FOLLOWUP_CNC', 'MQL_MARKETING_QUALIFIED_LEAD', 'ACTIVATION', 'OFFSITE_DELAYED', 'OFFSITE_DONE_LATE_REACHOUT', 'NOT_INTERESTED', 'CONNECT_LATER', 'CNC_COULD_NOT_CONNECT_3', 'CNC_COULD_NOT_CONNECT_2', 'CNC_COULD_NOT_CONNECT', 'DISQUALIFIED_WRONG_POC', 'INVALID_CONTACT', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED', 'YET_TO_BE_MINED'))
  , "previous_stage" TEXT CHECK ("previous_stage" IS NULL OR "previous_stage" IN ('SQL_SALES_QUALIFIED_LEAD', 'ACTIVE_REQUIREMENT_CALL_DONE_–_AWAITING_CLIENT_INPUTS', 'ACTIVE_REQUIREMENT_CALL_NO_SHOW', 'ACTIVE_REQUIREMENT_CALL_BOOKED', 'DISCOVERY_CALL_DONE_AWAITING_CLIENT_INPUTS', 'CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'DISCOVERY_CALL_BOOKED', 'FOLLOW_UP_1', 'FOLLOW_UP_2', 'FOLLOW_UP_3', 'FOLLOWUP_CNC', 'MQL_MARKETING_QUALIFIED_LEAD', 'ACTIVATION', 'OFFSITE_DELAYED', 'OFFSITE_DONE_LATE_REACHOUT', 'NOT_INTERESTED', 'CONNECT_LATER', 'CNC_COULD_NOT_CONNECT_3', 'CNC_COULD_NOT_CONNECT_2', 'CNC_COULD_NOT_CONNECT', 'DISQUALIFIED_WRONG_POC', 'INVALID_CONTACT', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED', 'YET_TO_BE_MINED'))
  , "vendor_info" TEXT CHECK ("vendor_info" IS NULL OR "vendor_info" IN ('Internal', 'Vendor Exists', 'First Event', 'No Info'))
  , "mode_of_meeting" TEXT CHECK ("mode_of_meeting" IS NULL OR "mode_of_meeting" IN ('In Person', 'Virtual', 'Calls', 'Text'))
  , "next_call_date" TEXT CHECK ("next_call_date" IS NULL OR "next_call_date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
  , "next_call_time" TEXT
  , "service_offering" INTEGER NOT NULL DEFAULT 0 CHECK ("service_offering" IN (0, 1))
  -- Set true the first time a non-CNC stage is seen, never unset. This is what makes Phone Picked monotonic.
  , "ever_picked" INTEGER NOT NULL DEFAULT 0 CHECK ("ever_picked" IN (0, 1))
  -- Highest rung ever reached. Written as MAX(existing, computed). Never decreases.
  , "kpi_rank" INTEGER
  -- When KPI Rank last increased — the last qualitative update.
  , "kpi_rank_at" TEXT CHECK ("kpi_rank_at" IS NULL OR "kpi_rank_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- First call ever logged against this contact. Written once, never updated.
  , "first_worked_at" TEXT CHECK ("first_worked_at" IS NULL OR "first_worked_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- First time this contact reached a stage that is not a no-answer — the moment somebody actually spoke to them. Written once, never updated.
  , "first_picked_at" TEXT CHECK ("first_picked_at" IS NULL OR "first_picked_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- Captured in the console but not yet in Kylas. Tells the writer POST rather than PUT.
  , "pending_create" INTEGER NOT NULL DEFAULT 0 CHECK ("pending_create" IN (0, 1))
  -- Set when the contact lands on a dead-end stage. Kept apart from KPI Rank so an exit cannot pull the funnel backwards.
  , "exit_reason" TEXT CHECK ("exit_reason" IS NULL OR "exit_reason" IN ('CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'NOT_INTERESTED', 'INVALID_CONTACT', 'DISQUALIFIED_WRONG_POC', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED'))
  , "flagged" INTEGER NOT NULL DEFAULT 0 CHECK ("flagged" IN (0, 1))
  -- was the Airtable link "Company" → Companies
  , "company_id" INTEGER REFERENCES "companies"("id") ON DELETE RESTRICT
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("kylas_contact_id")
);

-- Past and current event rows. Hangs off the contact, not the company.
CREATE TABLE IF NOT EXISTS "event_rows" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- UUID assigned by the overlay. Upsert key.
  , "row_key" TEXT
  , "period" TEXT CHECK ("period" IS NULL OR "period" IN ('Past', 'Current'))
  , "event_type" TEXT
  , "budget" TEXT
  , "timeline" TEXT
  , "pax" TEXT
  , "remarks" TEXT
  -- was the Airtable link "Contact" → Contacts
  , "contact_id" INTEGER REFERENCES "contacts"("id") ON DELETE RESTRICT
  -- derived on this row only; a child-dependent field would belong in a view
  , "has_any_signal" INTEGER GENERATED ALWAYS AS (CASE WHEN COALESCE("budget", '') <> '' OR COALESCE("timeline", '') <> '' OR COALESCE("pax", '') <> '' THEN 1 ELSE 0 END) STORED
  -- derived on this row only; a child-dependent field would belong in a view
  , "is_complete" INTEGER GENERATED ALWAYS AS (CASE WHEN COALESCE("budget", '') <> '' AND COALESCE("timeline", '') <> '' AND COALESCE("pax", '') <> '' THEN 1 ELSE 0 END) STORED
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("row_key")
);

-- One row per save in the console, whether or not the stage moved. Append-only — never update or delete a row here.
CREATE TABLE IF NOT EXISTS "call_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- Idempotency key from the overlay, so a retried save does not double-count.
  , "key" TEXT
  , "called_at" TEXT CHECK ("called_at" IS NULL OR "called_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  , "outcome" TEXT CHECK ("outcome" IS NULL OR "outcome" IN ('No answer', 'Wrong POC', 'Right POC', 'Discovery'))
  -- Seconds.
  , "duration" INTEGER
  -- dialed is measured; estimated is inferred from the outcome keypress; none means no outcome was set.
  , "duration_source" TEXT CHECK ("duration_source" IS NULL OR "duration_source" IN ('dialed', 'estimated', 'none'))
  , "owner" TEXT
  , "stage_set" TEXT CHECK ("stage_set" IS NULL OR "stage_set" IN ('SQL_SALES_QUALIFIED_LEAD', 'ACTIVE_REQUIREMENT_CALL_DONE_–_AWAITING_CLIENT_INPUTS', 'ACTIVE_REQUIREMENT_CALL_NO_SHOW', 'ACTIVE_REQUIREMENT_CALL_BOOKED', 'DISCOVERY_CALL_DONE_AWAITING_CLIENT_INPUTS', 'CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'DISCOVERY_CALL_BOOKED', 'FOLLOW_UP_1', 'FOLLOW_UP_2', 'FOLLOW_UP_3', 'FOLLOWUP_CNC', 'MQL_MARKETING_QUALIFIED_LEAD', 'ACTIVATION', 'OFFSITE_DELAYED', 'OFFSITE_DONE_LATE_REACHOUT', 'NOT_INTERESTED', 'CONNECT_LATER', 'CNC_COULD_NOT_CONNECT_3', 'CNC_COULD_NOT_CONNECT_2', 'CNC_COULD_NOT_CONNECT', 'DISQUALIFIED_WRONG_POC', 'INVALID_CONTACT', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED', 'YET_TO_BE_MINED'))
  , "created_here" INTEGER NOT NULL DEFAULT 0 CHECK ("created_here" IN (0, 1))
  , "next_call_date" TEXT CHECK ("next_call_date" IS NULL OR "next_call_date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
  -- was the Airtable link "Contact" → Contacts
  , "contact_id" INTEGER REFERENCES "contacts"("id") ON DELETE RESTRICT
  -- derived on this row only; a child-dependent field would belong in a view
  , "measured_seconds" INTEGER GENERATED ALWAYS AS (CASE WHEN "duration_source" = 'dialed' THEN COALESCE("duration", 0) ELSE 0 END) STORED
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- One row per stage change. Append-only — never update or delete a row here.
CREATE TABLE IF NOT EXISTS "stage_transitions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  , "key" TEXT
  , "from_stage" TEXT CHECK ("from_stage" IS NULL OR "from_stage" IN ('SQL_SALES_QUALIFIED_LEAD', 'ACTIVE_REQUIREMENT_CALL_DONE_–_AWAITING_CLIENT_INPUTS', 'ACTIVE_REQUIREMENT_CALL_NO_SHOW', 'ACTIVE_REQUIREMENT_CALL_BOOKED', 'DISCOVERY_CALL_DONE_AWAITING_CLIENT_INPUTS', 'CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'DISCOVERY_CALL_BOOKED', 'FOLLOW_UP_1', 'FOLLOW_UP_2', 'FOLLOW_UP_3', 'FOLLOWUP_CNC', 'MQL_MARKETING_QUALIFIED_LEAD', 'ACTIVATION', 'OFFSITE_DELAYED', 'OFFSITE_DONE_LATE_REACHOUT', 'NOT_INTERESTED', 'CONNECT_LATER', 'CNC_COULD_NOT_CONNECT_3', 'CNC_COULD_NOT_CONNECT_2', 'CNC_COULD_NOT_CONNECT', 'DISQUALIFIED_WRONG_POC', 'INVALID_CONTACT', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED', 'YET_TO_BE_MINED'))
  , "to_stage" TEXT CHECK ("to_stage" IS NULL OR "to_stage" IN ('SQL_SALES_QUALIFIED_LEAD', 'ACTIVE_REQUIREMENT_CALL_DONE_–_AWAITING_CLIENT_INPUTS', 'ACTIVE_REQUIREMENT_CALL_NO_SHOW', 'ACTIVE_REQUIREMENT_CALL_BOOKED', 'DISCOVERY_CALL_DONE_AWAITING_CLIENT_INPUTS', 'CLOSING_LOOPS_LOW_VALUE', 'GHOSTED', 'DISCOVERY_CALL_BOOKED', 'FOLLOW_UP_1', 'FOLLOW_UP_2', 'FOLLOW_UP_3', 'FOLLOWUP_CNC', 'MQL_MARKETING_QUALIFIED_LEAD', 'ACTIVATION', 'OFFSITE_DELAYED', 'OFFSITE_DONE_LATE_REACHOUT', 'NOT_INTERESTED', 'CONNECT_LATER', 'CNC_COULD_NOT_CONNECT_3', 'CNC_COULD_NOT_CONNECT_2', 'CNC_COULD_NOT_CONNECT', 'DISQUALIFIED_WRONG_POC', 'INVALID_CONTACT', 'NOT_A_DECISION_MAKER_NDM', 'POC_ORGANIZATION_CHANGED', 'YET_TO_BE_MINED'))
  , "changed_at" TEXT CHECK ("changed_at" IS NULL OR "changed_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  , "owner" TEXT
  , "source" TEXT CHECK ("source" IS NULL OR "source" IN ('Console', 'Kylas webhook', 'Backfill', 'Kylas sync'))
  -- Mode of Meeting as it stood when this stage was set. Blank for a move Kylas reported.
  , "mode" TEXT CHECK ("mode" IS NULL OR "mode" IN ('In Person', 'Virtual', 'Calls', 'Text'))
  -- was the Airtable link "Contact" → Contacts
  , "contact_id" INTEGER REFERENCES "contacts"("id") ON DELETE RESTRICT
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- One frozen row per day per owner. Written once after the day ends, never updated. Day/week/month reporting reads this, not a live recount.
CREATE TABLE IF NOT EXISTS "daily_snapshot" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- date · owner. Stops a day being frozen twice.
  , "key" TEXT
  , "date" TEXT CHECK ("date" IS NULL OR "date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
  , "owner" TEXT
  , "dials" INTEGER
  , "connects" INTEGER
  -- Reached this rung ON this day. A movement, not a total.
  , "new_right_poc" INTEGER
  , "new_discovery" INTEGER
  , "new_sql_booked" INTEGER
  , "new_sql_accepted" INTEGER
  , "companies_touched" INTEGER
  , "contacts_added" INTEGER
  -- Measured dials only, so this stays a real number.
  , "talk_seconds" INTEGER
  -- Where things STOOD at end of day. Summing across a week double-counts.
  , "companies_at_right_poc" INTEGER
  , "companies_at_discovery" INTEGER
  , "companies_at_sql_booked" INTEGER
  , "companies_at_sql_meeting_done" INTEGER
  , "companies_at_sql_accepted" INTEGER
  , "companies_reached_to_date" INTEGER
  , "connect_rate" REAL
  , "frozen_at" TEXT CHECK ("frozen_at" IS NULL OR "frozen_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- One row per day per owner per outcome, replacing the raw Call Log rows for days past the retention window. Written by rollup-calls.mjs. The period report reads this for old days and the raw log for recent ones.
CREATE TABLE IF NOT EXISTS "call_rollup" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- day|owner|outcome. The upsert key, so re-running a day overwrites rather than adds.
  , "key" TEXT
  , "day" TEXT
  , "owner" TEXT
  , "outcome" TEXT
  , "calls" INTEGER
  , "talk_seconds" INTEGER
  , "rolled_at" TEXT CHECK ("rolled_at" IS NULL OR "rolled_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- One row per company a BD has picked or dropped. The CURRENT state only — every change is also appended to Focus History, which is what makes 'who dropped this and why' answerable a month later.
CREATE TABLE IF NOT EXISTS "focus" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- Upsert key. The same id the route and Kylas use.
  , "kylas_company_id" TEXT
  -- Carried so the focus list reads without joining back.
  , "company_name" TEXT
  , "status" TEXT CHECK ("status" IS NULL OR "status" IN ('focus', 'depri'))
  -- Why it was dropped. Blank on a focus row — nobody is asked to justify picking one.
  , "reason" TEXT CHECK ("reason" IS NULL OR "reason" IN ('No event budget this year', 'Too small / not a fit', 'Events handled in-house', 'Locked in with another agency', 'Can''t reach the right POC', 'Timing — revisit next quarter', 'Other'))
  , "note" TEXT
  -- Whose list it is: the account owner at the time, NOT the person who set it. Kylas ownership goes stale and the list should not move under the BD.
  , "owner" TEXT
  -- Who actually clicked.
  , "set_by" TEXT
  , "set_at" TEXT CHECK ("set_at" IS NULL OR "set_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("kylas_company_id")
);

-- Append-only. Never updated, never deleted: the point of a focus list is what somebody decided and when, and an overwrite loses exactly that.
CREATE TABLE IF NOT EXISTS "focus_history" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- <kylas company id>-<iso timestamp>. Idempotent on a retry.
  , "key" TEXT
  , "kylas_company_id" TEXT
  , "from_status" TEXT CHECK ("from_status" IS NULL OR "from_status" IN ('focus', 'normal', 'depri'))
  , "to_status" TEXT CHECK ("to_status" IS NULL OR "to_status" IN ('focus', 'normal', 'depri'))
  , "reason" TEXT CHECK ("reason" IS NULL OR "reason" IN ('No event budget this year', 'Too small / not a fit', 'Events handled in-house', 'Locked in with another agency', 'Can''t reach the right POC', 'Timing — revisit next quarter', 'Other'))
  , "note" TEXT
  , "owner" TEXT
  , "set_by" TEXT
  , "changed_at" TEXT CHECK ("changed_at" IS NULL OR "changed_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- What a BD found out about a company before calling it. Fifteen fields, all free text, all optional — the shape comes from reference/enout-bd-ladder.html. Nothing here is synced from Kylas; this is the one table the ladder app owns outright.
CREATE TABLE IF NOT EXISTS "research" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- Upsert key.
  , "kylas_company_id" TEXT
  , "company_name" TEXT
  , "industry" TEXT
  , "employees" TEXT
  , "hq_city" TEXT
  , "other_offices" TEXT
  , "funding" TEXT
  , "revenue_band" TEXT
  , "known_events" TEXT
  , "event_season" TEXT
  , "decides_events" TEXT
  , "current_agency" TEXT
  , "recent_trigger" TEXT
  , "links" TEXT
  , "v_score" TEXT
  , "w_score" TEXT
  , "research_notes" TEXT
  , "updated_by" TEXT
  , "updated_at" TEXT CHECK ("updated_at" IS NULL OR "updated_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("kylas_company_id")
);

-- One row per stalled contact per gate. Asked by the console when a contact has sat at a rung past the gate's patience; answered by the associate. Reason codes come from docs/rca-reasons.json — see gen-rca.mjs.
CREATE TABLE IF NOT EXISTS "rca" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- <kylas contact id>|<gate key>. The upsert key: one open question per contact per gate, for ever.
  , "key" TEXT
  -- Which stall this is — see docs/rca-reasons.json.
  , "gate" TEXT CHECK ("gate" IS NULL OR "gate" IN ('rightNoDiscovery', 'discoveryNoBooking', 'doneNoSql'))
  -- When the console first listed it. Not when it became stuck.
  , "asked_at" TEXT CHECK ("asked_at" IS NULL OR "asked_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- The contact's KPI Rank At — when it arrived at the rung it is stuck on.
  , "stuck_since" TEXT CHECK ("stuck_since" IS NULL OR "stuck_since" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- Days between Stuck Since and the answer. Frozen at answer time, so a row read months later still says how long it had been when somebody looked.
  , "stuck_days" INTEGER
  -- Blank until answered. Codes, not labels — a label can be reworded without orphaning the history.
  , "reason" TEXT CHECK ("reason" IS NULL OR "reason" IN ('NO_SLOT', 'GHOSTING', 'NO_EVENT_PLANNED', 'BUDGET_NOT_SIGNED_OFF', 'NEEDS_SENIOR_BUY_IN', 'INCUMBENT_VENDOR', 'WRONG_FIT', 'MY_FOLLOW_UP_SLIPPED', 'OTHER', 'AWAITING_CLIENT_INPUTS', 'DATES_NOT_FIXED', 'BUDGET_TOO_LOW', 'COMPARING_VENDORS', 'DECISION_DEFERRED', 'LOST_INTERNAL_CHAMPION', 'PROPOSAL_PENDING_OUR_SIDE', 'SCOPE_MISMATCH', 'LOST_TO_COMPETITOR', 'EVENT_POSTPONED', 'NO_DECISION_MAKER', 'WENT_SILENT'))
  -- Free text. Optional, and the only place the specifics of one account can live.
  , "note" TEXT
  , "answered_at" TEXT CHECK ("answered_at" IS NULL OR "answered_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  , "answered_by" TEXT
  -- Whose account it was when the question was asked.
  , "owner" TEXT
  -- was the Airtable link "Contact" → Contacts
  , "contact_id" INTEGER REFERENCES "contacts"("id") ON DELETE RESTRICT
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- One row per person who may appear in the funnel. `In Funnel` alone decides whether their numbers are counted — Role is informational. Read by the dashboard, edited from the console's Team panel.
CREATE TABLE IF NOT EXISTS "team" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- Exactly as the Owner field spells it elsewhere in this base — that is what the report joins on.
  , "name" TEXT
  -- Free text, e.g. Business Development Associate. Informational only.
  , "role" TEXT
  -- Ticked = their calls and companies are counted in the team funnel and they get a column on the ladder.
  , "in_funnel" INTEGER NOT NULL DEFAULT 0 CHECK ("in_funnel" IN (0, 1))
  , "note" TEXT
  , "updated_at" TEXT CHECK ("updated_at" IS NULL OR "updated_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("name")
);

-- One row per migration applied to this base. Written by the migration scripts, read by them to refuse a second run. Do not delete a row unless you intend the migration to run again.
CREATE TABLE IF NOT EXISTS "schema_migrations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT
  -- the Airtable record id, so the backfill can re-run and the reconciler can join
  , "airtable_id" TEXT UNIQUE
  -- Stable id of the migration, e.g. ladder-2026-09-17-retire-reschedule-pending.
  , "key" TEXT
  , "applied_at" TEXT CHECK ("applied_at" IS NULL OR "applied_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*')
  -- What it changed, and how many rows.
  , "note" TEXT
  -- when this copy last changed, for the reconciler and for deltas
  , "synced_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  -- the key the application upserts on: a duplicate is a failed write, not a report
  , UNIQUE ("key")
);

-- ── indexes ─────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS "ix_contacts_company_id" ON "contacts" ("company_id");
CREATE INDEX IF NOT EXISTS "ix_event_rows_contact_id" ON "event_rows" ("contact_id");
CREATE INDEX IF NOT EXISTS "ix_call_log_contact_id" ON "call_log" ("contact_id");
CREATE INDEX IF NOT EXISTS "ix_call_log_called_at" ON "call_log" ("called_at");
CREATE INDEX IF NOT EXISTS "ix_call_log_owner_called_at" ON "call_log" ("owner", "called_at");
CREATE INDEX IF NOT EXISTS "ix_stage_transitions_contact_id" ON "stage_transitions" ("contact_id");
CREATE INDEX IF NOT EXISTS "ix_stage_transitions_changed_at" ON "stage_transitions" ("changed_at");
CREATE INDEX IF NOT EXISTS "ix_rca_contact_id" ON "rca" ("contact_id");
CREATE INDEX IF NOT EXISTS "ix_contacts_next_call_date" ON "contacts" ("next_call_date");
CREATE INDEX IF NOT EXISTS "ix_contacts_current_stage" ON "contacts" ("current_stage");
CREATE INDEX IF NOT EXISTS "ix_companies_kylas_owner_id" ON "companies" ("kylas_owner_id");
CREATE INDEX IF NOT EXISTS "ix_focus_history_kylas_company_id" ON "focus_history" ("kylas_company_id");
CREATE INDEX IF NOT EXISTS "ix_daily_snapshot_date_owner" ON "daily_snapshot" ("date", "owner");
CREATE INDEX IF NOT EXISTS "ix_call_rollup_day_owner" ON "call_rollup" ("day", "owner");
