#!/usr/bin/env node
/* Generates the RCA tables from docs/rca-reasons.json.
 *
 *   node scripts/gen-rca.mjs
 *
 * Same reason as gen-stages: the console runs in a browser and the scripts run
 * in node, and a reason list that exists twice will eventually differ. The
 * Airtable column is a singleSelect built from these codes, so a label the
 * console offers that the schema has never heard of is a rejected write — one
 * definition, both ends. Do not edit the generated files.
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = JSON.parse(readFileSync(new URL("../docs/rca-reasons.json", import.meta.url), "utf8"));
const GATES = src.gates || [];

/* The rungs a gate may name. These are the funnel keys the views and the
   Airtable mirror both use; a gate naming anything else would silently never
   fire, which is the worst way for a rule to be wrong. */
const RUNGS = ["reached", "picked", "right", "discovery", "booked", "done", "sql"];

if (!GATES.length) throw new Error("no gates defined");
for (const g of GATES) {
  for (const k of ["key", "from", "to", "title", "ask"])
    if (!g[k]) throw new Error(`gate ${g.key || "?"} has no ${k}`);
  if (!RUNGS.includes(g.from)) throw new Error(`gate ${g.key}: unknown from-rung ${g.from}`);
  if (!RUNGS.includes(g.to)) throw new Error(`gate ${g.key}: unknown to-rung ${g.to}`);
  if (RUNGS.indexOf(g.to) <= RUNGS.indexOf(g.from))
    throw new Error(`gate ${g.key}: ${g.to} is not past ${g.from} — a gate has to face forwards`);
  if (!Number.isFinite(g.days) || g.days < 1)
    throw new Error(`gate ${g.key}: days must be a positive number`);
  if (!g.reasons?.length) throw new Error(`gate ${g.key} offers no reasons`);
  const codes = g.reasons.map((r) => r.code);
  const dupe = codes.find((c, i) => codes.indexOf(c) !== i);
  if (dupe) throw new Error(`gate ${g.key}: duplicate reason code ${dupe}`);
  for (const r of g.reasons) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(r.code || ""))
      throw new Error(`gate ${g.key}: reason code ${JSON.stringify(r.code)} must be UPPER_SNAKE`);
    if (!r.label) throw new Error(`gate ${g.key}: reason ${r.code} has no label`);
  }
}
/* Two gates on one key would have the later one silently win in every Map
   built from this. */
const keys = GATES.map((g) => g.key);
const dk = keys.find((k, i) => keys.indexOf(k) !== i);
if (dk) throw new Error(`duplicate gate key: ${dk}`);

const q = (v) => JSON.stringify(v);
const HEAD = (what) => `/* GENERATED by scripts/gen-rca.mjs from docs/rca-reasons.json.
   ${what}
   Do not edit. Change the json and re-run the generator. */
`;

const gateBody = (g) => `  {
    key: ${q(g.key)},
    from: ${q(g.from)}, to: ${q(g.to)}, days: ${g.days},
    title: ${q(g.title)},
    ask: ${q(g.ask)},
    reasons: [
${g.reasons.map((r) => `      { code: ${q(r.code)}, label: ${q(r.label)} },`).join("\n")}
    ],
  },`;

/* Every reason code across every gate, which is what the Airtable singleSelect
   has to offer. One column rather than one per gate: the gate is already
   recorded on the row, and a select per gate would mean a schema change every
   time a gate is added. */
const ALL_CODES = [...new Set(GATES.flatMap((g) => g.reasons.map((r) => r.code)))];
const ALL_LABELS = [];
for (const g of GATES) for (const r of g.reasons)
  if (!ALL_LABELS.some(([c]) => c === r.code)) ALL_LABELS.push([r.code, r.label]);

/* NO BROWSER COPY, deliberately — gen-stages emits one and this does not.
   The console renders the reasons the proxy sends alongside the list of stalled
   accounts, so there is nothing for it to hold. A generated copy in the
   extension would be a second definition that is right until the day a proxy
   runs newer rules than a browser, and then silently offers a reason the base
   will reject. The gates travel with the question. */

/* ── node ────────────────────────────────────────────────────────── */
writeFileSync(new URL("./rca.mjs", import.meta.url),
HEAD("Imported by schema.mjs and the proxy.") + `
export const RCA_GATES = [
${GATES.map(gateBody).join("\n")}
];

export const RCA_LABEL = {
${ALL_LABELS.map(([c, l]) => `  ${(c + ":").padEnd(30)} ${q(l)},`).join("\n")}
};

export const RCA_GATE = Object.fromEntries(RCA_GATES.map((g) => [g.key, g]));

/* What the Airtable Reason column offers. */
export const RCA_REASON_CODES = ${q(ALL_CODES)};
export const RCA_GATE_KEYS = ${q(keys)};

/* ── WHO OWES AN EXPLANATION ──────────────────────────────────────────
   One definition, used by the proxy to build the list and by nothing else, so
   the console never has to agree with it — it is told.

   A contact is at a gate when it has reached \`from\`, has NOT reached \`to\`,
   and has sat there longer than the gate allows. "Sat there" is measured from
   KPI Rank At, which records when the rank last ROSE: for a contact that has
   not moved since, that is precisely the day it arrived. It is the only date
   in the base that answers this, and it only answers it for a contact that is
   stuck — which is the only contact being asked about.

   A contact with no KPI Rank At has never been seen to move, so there is no
   arrival to measure from and it is left alone rather than dated to the epoch
   and reported as 20,000 days overdue. */
export function gateFor(contact, now = Date.now()) {
  const at = Date.parse(contact.rankAt || "");
  if (!Number.isFinite(at)) return null;
  const days = Math.floor((now - at) / 86400000);
  for (const g of RCA_GATES) {
    if (!contact[g.from] || contact[g.to]) continue;
    if (days < g.days) continue;
    return { gate: g.key, days, since: new Date(at).toISOString() };
  }
  return null;
}
`);

console.log(`rca: ${GATES.length} gate(s), ${ALL_CODES.length} reason code(s) -> scripts/rca.mjs`);
for (const g of GATES)
  console.log(`  ${g.key}: ${g.from} -> ${g.to} after ${g.days}d, ${g.reasons.length} reasons`);
