/* GENERATED by scripts/gen-rca.mjs from docs/rca-reasons.json.
   Imported by schema.mjs and the proxy.
   Do not edit. Change the json and re-run the generator. */

export const RCA_GATES = [
  {
    key: "rightNoDiscovery",
    from: "right", to: "discovery", days: 30,
    title: "Right POC, no discovery call",
    ask: "You reached the right person here a month ago and the discovery call has not happened. What is holding it up?",
    reasons: [
      { code: "NO_SLOT", label: "Cannot get a slot in their diary" },
      { code: "GHOSTING", label: "Stopped replying after the first call" },
      { code: "NO_EVENT_PLANNED", label: "No event planned yet — too early" },
      { code: "BUDGET_NOT_SIGNED_OFF", label: "Budget not signed off" },
      { code: "NEEDS_SENIOR_BUY_IN", label: "Waiting on somebody more senior" },
      { code: "INCUMBENT_VENDOR", label: "Happy with their current vendor" },
      { code: "WRONG_FIT", label: "Not a fit for what we do" },
      { code: "MY_FOLLOW_UP_SLIPPED", label: "My own follow-up slipped" },
      { code: "OTHER", label: "Something else" },
    ],
  },
  {
    key: "discoveryNoBooking",
    from: "discovery", to: "booked", days: 21,
    title: "Discovery done, no SQL meeting booked",
    ask: "The discovery call happened and nothing is in the diary since. Why has it not converted?",
    reasons: [
      { code: "AWAITING_CLIENT_INPUTS", label: "Waiting on inputs they promised" },
      { code: "DATES_NOT_FIXED", label: "Their dates are not fixed yet" },
      { code: "BUDGET_TOO_LOW", label: "Budget too low for the ask" },
      { code: "COMPARING_VENDORS", label: "Comparing us against other vendors" },
      { code: "DECISION_DEFERRED", label: "Decision pushed to a later quarter" },
      { code: "LOST_INTERNAL_CHAMPION", label: "Lost the person championing it" },
      { code: "PROPOSAL_PENDING_OUR_SIDE", label: "Proposal still pending at our end" },
      { code: "MY_FOLLOW_UP_SLIPPED", label: "My own follow-up slipped" },
      { code: "OTHER", label: "Something else" },
    ],
  },
  {
    key: "doneNoSql",
    from: "done", to: "sql", days: 14,
    title: "SQL meeting held, still not qualified",
    ask: "The Active Requirement call happened and the account has not qualified since. What is standing in the way?",
    reasons: [
      { code: "AWAITING_CLIENT_INPUTS", label: "Waiting on inputs they promised" },
      { code: "SCOPE_MISMATCH", label: "Wants something we do not do" },
      { code: "BUDGET_TOO_LOW", label: "Budget too low for the ask" },
      { code: "LOST_TO_COMPETITOR", label: "Went with another agency" },
      { code: "EVENT_POSTPONED", label: "Event postponed or cancelled" },
      { code: "DECISION_DEFERRED", label: "Decision pushed to a later quarter" },
      { code: "NO_DECISION_MAKER", label: "The decision maker was not in the room" },
      { code: "PROPOSAL_PENDING_OUR_SIDE", label: "Proposal still pending at our end" },
      { code: "WENT_SILENT", label: "Stopped replying after the meeting" },
      { code: "MY_FOLLOW_UP_SLIPPED", label: "My own follow-up slipped" },
      { code: "OTHER", label: "Something else" },
    ],
  },
];

export const RCA_LABEL = {
  NO_SLOT:                       "Cannot get a slot in their diary",
  GHOSTING:                      "Stopped replying after the first call",
  NO_EVENT_PLANNED:              "No event planned yet — too early",
  BUDGET_NOT_SIGNED_OFF:         "Budget not signed off",
  NEEDS_SENIOR_BUY_IN:           "Waiting on somebody more senior",
  INCUMBENT_VENDOR:              "Happy with their current vendor",
  WRONG_FIT:                     "Not a fit for what we do",
  MY_FOLLOW_UP_SLIPPED:          "My own follow-up slipped",
  OTHER:                         "Something else",
  AWAITING_CLIENT_INPUTS:        "Waiting on inputs they promised",
  DATES_NOT_FIXED:               "Their dates are not fixed yet",
  BUDGET_TOO_LOW:                "Budget too low for the ask",
  COMPARING_VENDORS:             "Comparing us against other vendors",
  DECISION_DEFERRED:             "Decision pushed to a later quarter",
  LOST_INTERNAL_CHAMPION:        "Lost the person championing it",
  PROPOSAL_PENDING_OUR_SIDE:     "Proposal still pending at our end",
  SCOPE_MISMATCH:                "Wants something we do not do",
  LOST_TO_COMPETITOR:            "Went with another agency",
  EVENT_POSTPONED:               "Event postponed or cancelled",
  NO_DECISION_MAKER:             "The decision maker was not in the room",
  WENT_SILENT:                   "Stopped replying after the meeting",
};

export const RCA_GATE = Object.fromEntries(RCA_GATES.map((g) => [g.key, g]));

/* What the Airtable Reason column offers. */
export const RCA_REASON_CODES = ["NO_SLOT","GHOSTING","NO_EVENT_PLANNED","BUDGET_NOT_SIGNED_OFF","NEEDS_SENIOR_BUY_IN","INCUMBENT_VENDOR","WRONG_FIT","MY_FOLLOW_UP_SLIPPED","OTHER","AWAITING_CLIENT_INPUTS","DATES_NOT_FIXED","BUDGET_TOO_LOW","COMPARING_VENDORS","DECISION_DEFERRED","LOST_INTERNAL_CHAMPION","PROPOSAL_PENDING_OUR_SIDE","SCOPE_MISMATCH","LOST_TO_COMPETITOR","EVENT_POSTPONED","NO_DECISION_MAKER","WENT_SILENT"];
export const RCA_GATE_KEYS = ["rightNoDiscovery","discoveryNoBooking","doneNoSql"];

/* ── WHO OWES AN EXPLANATION ──────────────────────────────────────────
   One definition, used by the proxy to build the list and by nothing else, so
   the console never has to agree with it — it is told.

   A contact is at a gate when it has reached `from`, has NOT reached `to`,
   and has sat there longer than the gate allows. "Sat there" is measured from
   KPI Rank At, which records when the rank last ROSE: for a contact that has
   not moved since, that is precisely the day it arrived. It is the only date
   in the base that answers this, and it only answers it for a contact that is
   stuck — which is the only contact being asked about.

   A contact with no KPI Rank At has never been seen to move, so there is no
   arrival to measure from and it is left alone rather than dated to the epoch
   and reported as 20,000 days overdue. */
export function gateFor(contact, now = Date.now()) {
  const at = Date.parse(contact.rankAt || "");
  if (!Number.isFinite(at)) return null;
  const days = Math.floor((now - at) / 86400000);
  for (const g of RCA_GATES) {
    if (!contact[g.from] || contact[g.to]) continue;
    if (days < g.days) continue;
    return { gate: g.key, days, since: new Date(at).toISOString() };
  }
  return null;
}
