#!/usr/bin/env node
/* THE DERIVED NUMBERS, AS VIEWS.
 *
 *   node scripts/sql-derived.mjs            # print the view DDL
 *   node scripts/sql-derived.mjs --out db/derived.sql
 *
 * Airtable computes 41 fields for us. Three of them read only their own row
 * and are generated columns (sql-schema.mjs); the other 38 read a CHILD table,
 * and those are these views.
 *
 * WHY VIEWS AND NOT COLUMNS — the one thing to understand about this file.
 * Airtable recomputes a company's rollup when an EVENT ROW changes, two levels
 * below it. A SQLite stored generated column recomputes only when its own row
 * is written, so a company whose grandchild changed would keep the old number
 * and look perfectly fine. A view has no stored value to go stale: it is the
 * query, run when read. That costs a join on every read and buys the one
 * property that matters, which is being right.
 *
 * The chain is two deep, so the views stack: v_contacts rolls up event rows,
 * calls and transitions; v_companies rolls up v_contacts.
 *
 * WHAT IS HAND-WRITTEN AND WHAT IS NOT. The view bodies are written here,
 * because translating Airtable's formula language mechanically would be a
 * compiler and a compiler is a second thing to be wrong. What is NOT left to
 * hand is the LIST: test-sql-derived.mjs reads FOLLOWUPS and fails if any
 * derived field has no column in the view that should hold it. Adding a rollup
 * in schema.mjs and forgetting it here is a failing test, not a missing number.
 * The ladder and the milestone floors are generated from stages.mjs for the
 * same reason.
 */
import { writeFileSync } from "node:fs";
import { LADDER, MILESTONE } from "./stages.mjs";

/* Airtable's epoch for the KPI score: DATETIME_DIFF(x, 1970-01-01, 'seconds').
   strftime('%s') is the same number, and CAST keeps it an integer — REAL
   arithmetic on a value near 2.6e11 loses the low digits, which are the
   timestamp half of the score. */
const SECONDS = (col) => `CAST(strftime('%s', ${col}) AS INTEGER)`;
const RANK_SCALE = 10000000000;

/* IF(rank = 1, "01 · …", IF(rank = 2, …)) — generated, so a stage added to
   docs/stages.json appears here without anybody editing SQL. */
const ladderCase = (rank) =>
  `CASE ${LADDER.slice(1).map(([n, label]) => `WHEN ${rank} = ${n} THEN '${label.replace(/'/g, "''")}'`).join(" ")} ` +
  `ELSE '${LADDER[0][1].replace(/'/g, "''")}' END`;

export function sqlDerived() {
  const out = [];
  out.push(`-- The derived KPI fields, as views.`);
  out.push(`-- GENERATED by scripts/sql-derived.mjs — do not edit by hand.`);
  out.push(`-- Views, not stored columns: a stored value does not recompute when a`);
  out.push(`-- GRANDCHILD changes, and Airtable's rollups do. See the file header.`);
  out.push(``);

  /* ── contacts ──────────────────────────────────────────────────────
     One row per contact, with every field Airtable derives from its event
     rows, its calls and its stage changes.

     The aggregates are computed in a WITH rather than as correlated
     subqueries so each child table is scanned once per read instead of once
     per contact — on 80 contacts either is instant, on 80,000 only one is. */
  out.push(`DROP VIEW IF EXISTS "v_contacts";`);
  out.push(`CREATE VIEW "v_contacts" AS
WITH ev AS (
  SELECT contact_id,
         MAX("has_any_signal") AS has_signal,
         MAX("is_complete")    AS has_complete_row
  FROM "event_rows" WHERE contact_id IS NOT NULL GROUP BY contact_id
),
cl AS (
  SELECT contact_id,
         COUNT("called_at")        AS call_count,
         MAX("called_at")          AS last_call_at,
         MIN("called_at")          AS first_call_at,
         SUM("measured_seconds")   AS talk_seconds,
         COUNT(*)                  AS measured_calls
  FROM "call_log" WHERE contact_id IS NOT NULL GROUP BY contact_id
),
st AS (
  SELECT contact_id,
         MAX("changed_at") AS last_stage_change_at,
         MIN("changed_at") AS first_stage_change_at
  FROM "stage_transitions" WHERE contact_id IS NOT NULL GROUP BY contact_id
)
SELECT
  c."id",
  c."airtable_id",
  c."kylas_contact_id",
  c."name",
  c."company_id",
  -- the company's Kylas id on the contact, so contacts can be filtered by
  -- company without a join at the call site
  co."kylas_company_id"                              AS "company_kylas_id",
  COALESCE(ev.has_signal, 0)                         AS "has_signal",
  COALESCE(ev.has_complete_row, 0)                   AS "has_complete_row",
  COALESCE(cl.call_count, 0)                         AS "call_count",
  cl.last_call_at                                    AS "last_call_at",
  cl.first_call_at                                   AS "first_call_at",
  COALESCE(cl.talk_seconds, 0)                       AS "talk_seconds",
  COALESCE(cl.measured_calls, 0)                     AS "measured_calls",
  -- across ALL calls; an estimated duration counts as 0, so read it beside
  -- talk_seconds rather than on its own
  CASE WHEN COALESCE(cl.call_count, 0) > 0
       THEN CAST(ROUND(COALESCE(cl.talk_seconds, 0) * 1.0 / cl.call_count) AS INTEGER)
       ELSE 0 END                                    AS "avg_call_seconds",
  st.last_stage_change_at                            AS "last_stage_change_at",
  st.first_stage_change_at                           AS "first_stage_change_at",
  CASE WHEN COALESCE(ev.has_signal, 0) = 1 THEN 1 ELSE 0 END        AS "is_right_poc",
  CASE WHEN COALESCE(ev.has_signal, 0) = 1 THEN c."name" ELSE '' END AS "right_poc_name",
  CASE WHEN COALESCE(ev.has_complete_row, 0) = 1 THEN 1 ELSE 0 END  AS "is_discovery",
  CASE WHEN COALESCE(ev.has_complete_row, 0) = 1 THEN c."name" ELSE '' END AS "discovery_name",
  ${ladderCase('COALESCE(c."kpi_rank", 0)')}         AS "kpi_stage",
  -- rank in the high digits, the moment it was reached in the low ones, so a
  -- single MAX at company level gives the best rung and, among ties, the most
  -- recent. The same packing Airtable's formula does.
  CASE WHEN c."kpi_rank_at" IS NOT NULL
       THEN COALESCE(c."kpi_rank", 0) * ${RANK_SCALE} + ${SECONDS('c."kpi_rank_at"')}
       ELSE COALESCE(c."kpi_rank", 0) * ${RANK_SCALE} END AS "kpi_score"
FROM "contacts" c
LEFT JOIN "companies" co ON co."id" = c."company_id"
LEFT JOIN ev ON ev.contact_id = c."id"
LEFT JOIN cl ON cl.contact_id = c."id"
LEFT JOIN st ON st.contact_id = c."id";`);
  out.push(``);

  /* ── companies ─────────────────────────────────────────────────────
     Rolls up v_contacts, which is what makes the grandchild case work: an
     event row changes, v_contacts recomputes because it is a view, and this
     recomputes because it reads that one. Nothing is stored anywhere along
     the chain, so nothing can be stale.

     group_concat is ORDERED explicitly. Airtable's ARRAYJOIN follows the
     linked-record order; SQLite's is unspecified without an ORDER BY, which
     would make two reads of the same unchanged data disagree. Ordering by
     contact id makes it stable. It may still differ from Airtable's order,
     which is why the reconciler compares these two fields as sets of names
     rather than as strings. */
  const M = MILESTONE;
  out.push(`DROP VIEW IF EXISTS "v_companies";`);
  out.push(`CREATE VIEW "v_companies" AS
WITH ct AS (
  SELECT v."company_id"                                        AS company_id,
         MAX(v."last_call_at")                                 AS last_call_at,
         MIN(v."first_call_at")                                AS first_call_at,
         -- MIN, so a company counts from the period its FIRST contact was
         -- worked rather than its latest one
         MIN(c."first_worked_at")                              AS first_worked_at,
         MIN(c."first_picked_at")                              AS first_picked_at,
         SUM(v."call_count")                                   AS call_count,
         SUM(v."talk_seconds")                                 AS talk_seconds,
         MAX(c."ever_picked")                                  AS ever_picked,
         MAX(v."kpi_score")                                    AS kpi_score,
         COUNT(v."name")                                       AS contact_count,
         group_concat(NULLIF(v."right_poc_name", ''), ', ')    AS right_poc_contacts,
         group_concat(NULLIF(v."discovery_name", ''), ', ')    AS discovery_contacts
  FROM "v_contacts" v
  JOIN "contacts" c ON c."id" = v."id"
  WHERE v."company_id" IS NOT NULL
  GROUP BY v."company_id"
)
SELECT
  co."id",
  co."airtable_id",
  co."kylas_company_id",
  co."name",
  ct.last_call_at                             AS "last_call_at",
  ct.first_call_at                            AS "first_call_at",
  ct.first_worked_at                          AS "first_worked_at",
  ct.first_picked_at                          AS "first_picked_at",
  COALESCE(ct.call_count, 0)                  AS "call_count",
  COALESCE(ct.talk_seconds, 0)                AS "talk_seconds",
  COALESCE(ct.ever_picked, 0)                 AS "ever_picked",
  COALESCE(ct.kpi_score, 0)                   AS "kpi_score",
  COALESCE(ct.contact_count, 0)               AS "contact_count",
  COALESCE(ct.right_poc_contacts, '')         AS "right_poc_contacts",
  COALESCE(ct.discovery_contacts, '')         AS "discovery_contacts",
  CASE WHEN ct.last_call_at IS NOT NULL THEN 1 ELSE 0 END           AS "reached",
  CASE WHEN COALESCE(ct.ever_picked, 0) = 1 THEN 1 ELSE 0 END       AS "phone_picked",
  CASE WHEN COALESCE(ct.right_poc_contacts, '') <> '' THEN 1 ELSE 0 END AS "right_poc",
  -- a complete row has all three filled, so it also has any one: Discovery is
  -- always a subset of Right POC and the funnel reads straight down
  CASE WHEN COALESCE(ct.discovery_contacts, '') <> '' THEN 1 ELSE 0 END AS "successful_discovery",
  CAST(COALESCE(ct.kpi_score, 0) / ${RANK_SCALE} AS INTEGER)        AS "kpi_rank",
  -- the three stage milestones are floors on the ladder. KPI Rank only ever
  -- rises, so "ever reached it" needs no history — the rank IS the high-water
  -- mark, and Booked counts a company whose call was booked and then no-showed
  CASE WHEN CAST(COALESCE(ct.kpi_score, 0) / ${RANK_SCALE} AS INTEGER) >= ${M.sqlMeetingBooked.floor} THEN 1 ELSE 0 END AS "sql_meeting_booked",
  CASE WHEN CAST(COALESCE(ct.kpi_score, 0) / ${RANK_SCALE} AS INTEGER) >= ${M.sqlMeetingDone.floor} THEN 1 ELSE 0 END AS "sql_meeting_done",
  CASE WHEN CAST(COALESCE(ct.kpi_score, 0) / ${RANK_SCALE} AS INTEGER) >= ${M.sql.floor} THEN 1 ELSE 0 END AS "sql",
  ${ladderCase(`CAST(COALESCE(ct.kpi_score, 0) / ${RANK_SCALE} AS INTEGER)`)} AS "kpi_stage",
  -- when it last moved up a rung: the low half of the score, read back out
  CASE WHEN COALESCE(ct.kpi_score, 0) > 0
       THEN strftime('%Y-%m-%dT%H:%M:%SZ', COALESCE(ct.kpi_score, 0) % ${RANK_SCALE}, 'unixepoch')
       ELSE NULL END                          AS "kpi_stage_at"
FROM "companies" co
LEFT JOIN ct ON ct.company_id = co."id";`);
  out.push(``);
  return out.join("\n");
}

/* Which view is supposed to hold each table's derived fields. The test reads
   this, so a field added to schema.mjs with nowhere to live fails rather than
   going missing. */
export const VIEW_FOR = { Contacts: "v_contacts", Companies: "v_companies" };

if (import.meta.url === `file://${process.argv[1]}`) {
  const sql = sqlDerived();
  const i = process.argv.indexOf("--out");
  if (i >= 0 && process.argv[i + 1]) {
    writeFileSync(process.argv[i + 1], sql);
    console.log(`wrote ${process.argv[i + 1]} — 2 views over 4 child tables`);
  } else process.stdout.write(sql);
}
